### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by xematin** [nikandr-surkov/Notcoin-Telegram-Mini-App-Clone#4]
root@Awmirr:~/Notcoin-Telegram-Mini-App-Clone# npm run dev

> notcoin-telegram-mini-app-clone@0.0.0 dev
> vite

file:///root/Notcoin-Telegram-Mini-App-Clone/node_modules/vite/bin/vite.js:7
    await import('source-map-support').then((r) => r.default.install())
    ^^^^^

SyntaxError: Unexpected reserved word
    at Loader.moduleStrategy (internal/modules/esm/translators.js:133:18)
    at async link (internal/modules/esm/module_job.js:42:21)

**Comment by Share2k** [comment]
Please check this trx hash I lost 10000 not  (my notcoin vouchers) help me
